<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Engagement.Domain\Engagement.Domain.csproj" />
    <ProjectReference Include="..\Engagement.Contracts\Engagement.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Engagement.Infrastructure" />
  </ItemGroup>
</Project>

